### ISSUE TITLE
ValueError: Trying to use model to hydrogenate, but no model provided.

### ISSUE THREAD

**Issue by liquidslr** [RokasEl/simgen#24]
Getting this error when trying to do a simple unconstained generation
`ValueError: Trying to use model to hydrogenate, but no model provided.`

Please let me know how to resolve this issue.

**Comment by RokasEl** [comment]
Hi, can you give me more info on how you're trying to do the generation? I.e. are you hosting a local copy of ZnDraw and doing it interactively, or are you using the CLI? If you're using the CLI, could you please post your full bash command?
